title: Ryosuke Takata
description: Ryosuke Takata, 高田 亮介
copyright: (c) Ryosuke Takata
researchmap_username: bonochof
twitter_username: bonochof
github_username:  bonochof
facebook_username: ryosuke.takata.9
youtube_username: UCF8ViNqQffiG0WvSjP-bfNQ
scholar_username: vT30-UUAAAAJ

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
